<?php _e('messages', 'ticketsys'); ?>
<?php _e('users', 'ticketsys'); ?>
<?php _e('products', 'ticketsys'); ?>
<?php _e('divisions', 'ticketsys'); ?>
<?php _e('email', 'ticketsys'); ?>
<?php _e('backup', 'ticketsys'); ?>
<?php _e('stats', 'ticketsys'); ?>
<?php _e('faq', 'ticketsys'); ?>
<?php _e('settings', 'ticketsys'); ?>